import type { WeatherModelInfo } from "./types";

export const WEATHER_MODELS: WeatherModelInfo[] = [
  {
    id: "icon_d2",
    label: "ICON-D2 (DWD)",
    provider: "DWD",
    resolutionKm: 2.1,
    region: "DACH",
    horizonHours: 48,
  },
  {
    id: "icon_eu",
    label: "ICON-EU (DWD)",
    provider: "DWD",
    resolutionKm: 6.5,
    region: "Europa",
    horizonHours: 120,
  },
  {
    id: "icon_seamless",
    label: "ICON Seamless",
    provider: "DWD",
    resolutionKm: 11,
    region: "Global",
    horizonHours: 180,
  },
  {
    id: "ecmwf_ifs025",
    label: "ECMWF IFS 0.25°",
    provider: "ECMWF",
    resolutionKm: 25,
    region: "Global",
    horizonHours: 240,
  },
  {
    id: "ecmwf_aifs025",
    label: "ECMWF AIFS",
    provider: "ECMWF",
    resolutionKm: 25,
    region: "Global KI",
    horizonHours: 240,
  },
  {
    id: "gfs_seamless",
    label: "GFS (NOAA)",
    provider: "NOAA",
    resolutionKm: 25,
    region: "Global",
    horizonHours: 240,
  },
  {
    id: "meteofrance_arome_france",
    label: "AROME (Météo-France)",
    provider: "Météo-France",
    resolutionKm: 1.3,
    region: "Frankreich/Alpenraum",
    horizonHours: 48,
  },
  {
    id: "meteofrance_arpege_europe",
    label: "ARPEGE Europe",
    provider: "Météo-France",
    resolutionKm: 10,
    region: "Europa",
    horizonHours: 120,
  },
  {
    id: "knmi_seamless",
    label: "HARMONIE/KNMI",
    provider: "KNMI",
    resolutionKm: 2,
    region: "Nordwesteuropa",
    horizonHours: 60,
  },
  {
    id: "dmi_seamless",
    label: "DMI Seamless",
    provider: "DMI",
    resolutionKm: 2.5,
    region: "Nordeuropa",
    horizonHours: 60,
  },
  {
    id: "gem_seamless",
    label: "GEM (Kanada)",
    provider: "MSC",
    resolutionKm: 15,
    region: "Global",
    horizonHours: 240,
  },
  {
    id: "ukmo_seamless",
    label: "UKMO Seamless",
    provider: "UK Met Office",
    resolutionKm: 10,
    region: "Europa/Global",
    horizonHours: 168,
  },
];
