/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MapRouteImport } from './routes/map'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ForecastMapsRouteImport } from './routes/forecast-maps'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastMapsRoute = ForecastMapsRouteImport.update({
  id: '/forecast-maps',
  path: '/forecast-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/forecast-maps': typeof ForecastMapsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/forecast-maps': typeof ForecastMapsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/forecast-maps': typeof ForecastMapsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/forecast-maps'
    | '/learn'
    | '/map'
    | '/models'
    | '/settings'
    | '/stations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/forecast-maps'
    | '/learn'
    | '/map'
    | '/models'
    | '/settings'
    | '/stations'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analysis'
    | '/forecast-maps'
    | '/learn'
    | '/map'
    | '/models'
    | '/settings'
    | '/stations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  ForecastMapsRoute: typeof ForecastMapsRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  StationsRoute: typeof StationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast-maps': {
      id: '/forecast-maps'
      path: '/forecast-maps'
      fullPath: '/forecast-maps'
      preLoaderRoute: typeof ForecastMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  ForecastMapsRoute: ForecastMapsRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  StationsRoute: StationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
